<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Zetl.Linux.Spike</AssemblyName>
    <RootNamespace>ZETL.LinuxSpike</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chordl\Chordl.csproj" />
  </ItemGroup>
</Project>
